# on:
#   push:

# name: Change infrastructure with Terraform

# jobs:
#   deploy_infra:
#     name: Deploy
#     runs-on: ubuntu-latest
#     environment: production

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1
    
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with: 
#          terraform_version: 0.14.5
     
#     - name: Terraform init
#       run: |
#         terraform init
#         terraform plan

#     - name: Terraform apply
#       if: ${{ github.ref == 'refs/heads/main' }}
#       run: echo Running only on $GITHUB_REF
#       #run: terraform apply -auto-approve

# This is a basic workflow to help you get started with Actions

name: Env

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build pkg
    runs-on: ubuntu-latest
    steps:
      - name: Run every time
        run: echo Hello, world!

  deploy_prod:
    name: Deploy on Production
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy pkg on production
        run: echo Step approved!
